spring:
  datasource:
    url: jdbc:mysql://${DB_ADDRESS:localhost}:${DB_PORT:3306}/${DB_DATABASE:employee_management}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
